### ISSUE TITLE
What are the differences compared with the official pytorch implementation?

### ISSUE THREAD

**Issue by Honlan** [taki0112/FUNIT-Tensorflow#1]
Hi taki:
      I have followed you for a long time and benefit a lot from your open-source projects.
      May I ask a question about this repository?
      You say that this repository is a simple tensorflow implementation of FUNIT, so compared with the official pytorch project, what are the main differences?
      I find that you change the "iteration" from 10W to 80W, and set the number of MLP layers from 3 to 2. Anything else?
     Looking forwards to your reply.

**Comment by taki0112** [comment]
There is no architecture difference.
"Simple" means that is code easy to read.

**Comment by Honlan** [comment]
Awesome!!!
I love TensorFlow!!!
